FROM node:20-alpine

WORKDIR /app

# Copia o package.json e o package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código da aplicação
COPY . .

EXPOSE 5000

CMD ["node", "index.js"]